GR: implement Rumor-sower
keyteki/keyteki pull request #3681
Opened 2024-01-09 06:04 UTC by strib

2024-01-11 21:56 UTC, romanogit commented on test/server/cards/07-GR/RumorSower.spec.js
> +        it('allows stunning a friendly creature', function () {
it should not allow friendly creature

2024-01-11 21:57 UTC, romanogit requested changes

2024-01-11 21:57 UTC, romanogit commented on test/server/cards/07-GR/RumorSower.spec.js
> +        it('allows stunning a friendly creature', function () {
it should not allow friendly creature

2024-01-12 00:36 UTC, strib commented on test/server/cards/07-GR/RumorSower.spec.js
> +        it('allows stunning a friendly creature', function () {
Ooops, great catch.  Fixed, thanks.

2024-01-12 12:10 UTC, merged